config/routes.rb
Intrnhuntr::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controller => { :registrations => 'registrations' }

  as :user do
  	# get '/profile' => 'users#show'
  	get '/login' => 'devise/sessions#new'
  	delete '/logout' => 'devise/sessions#destroy'
  	get '/favorites' => 'users#favorites'
  	get '/signup' => 'registrations#new'
  end

	resources :companies, :only => [:show, :index]
	resources :notepads, :only => :update
  resources :relationships, :only => [:create, :destroy]
  resources :orders

  root :to => 'pages#home'

  match '/services', :to => 'pages#services'
  match '*path', :to => 'pages#home'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :notes, :resume, :paid
  attr_accessor :resume_content_type

  has_many :relationships, foreign_key: "favoriter_id", dependent: :destroy
  has_many :favorited_companies, through: :relationships, source: :favorited

  has_one :notepad, dependent: :destroy
  has_one :order

  has_attached_file :resume,
                    :storage => :dropbox,
                    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
                    :dropbox_options => {
                      :path => proc { |resume| "resumes/#{id}/#{name}" }
                    }

  validates_attachment :resume, content_type: { content_type: /^application\/(msword|pdf)/ }

  def favorite!(company)
    relationships.create(favorited_id: company.id)
  end

  def favorited?(company)
    relationships.find_by_favorited_id(company.id) ? true : false
  end

  def unfavorite!(company)
    relationships.find_by_favorited_id(company.id).destroy
  end

  def favorites(page)
    favorited_companies.page(page)
  end

  def make_notepad
  	Notepad.create(user_id: self.id, content: "")
  end

  def paid?
    self.paid
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!

## don't need a profile page right now
#  def show
#  	@user = User.find(current_user.id)
#  end

  def favorites
  	@favorites = current_user.favorites params[:page] #favorited_companies.page(params[:page])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_favorite.html.erb
<%= form_for(current_user.relationships.build(favorited_id: company.id), remote: true) do |f| %>
  <div><%= f.hidden_field :favorited_id %></div>
  <%= image_submit_tag("star_yellow.png", class: "favorite") %>
<% end %>

app/views/users/_favorite_form.html.erb
<div id="favorite_form">
  <% if current_user.favorited? company %>
    <%= render 'unfavorite', company: company %>
  <% else %>
    <%= render 'favorite', company: company %>
  <% end %>
</div>

app/views/users/_unfavorite.html.erb
<%= form_for(current_user.relationships.find_by_favorited_id(company), html: { method: :delete }, remote: true) do |f| %>
  <%= image_submit_tag("star_red.png", class: "favorite") %>
<% end %>

app/views/users/favorites.html.erb
<% provide(:title, "Favorites") %>
<h1 class="center">Favorites</h1>
<div class="row center">
    <% if !@favorites.empty? %>
      <table class="table">
        <% @favorites.each do |f| %>
          <tr id="item">
            <td><%= link_to f.name, f %></td>
            <td><%= f.area %></td>
            <td><%= number_to_currency(f.salary, precision: 0) %></td>
            <td><%= render 'favorite_form', company: f %></td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <% flash.now[:notice] = "You don't have any favorites" %>
    <% end %>
    <br>
    <% if current_user.paid? %>
        <% if current_user.resume_file_size != nil %>
          <p>View your <%= link_to 'resume', current_user.resume.url(download: true) %></p>
        <% else %>
          <p>You don't have an uploaded resume. This can be done from your <%= link_to 'settings', edit_user_registration_path %></p>
        <% end %>
    <% else %>
        <div class="mini"><%= ilink_to 'lightbulb', 'Click Here To Get Resume Critique & Tips For Only $5', new_order_path, class: 'btn btn-primary btn-block' %></div>
    <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p>Find me in app/views/users/show.html.erb</p>