config/routes.rb
Intrnhuntr::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controller => { :registrations => 'registrations' }

  as :user do
  	# get '/profile' => 'users#show'
  	get '/login' => 'devise/sessions#new'
  	delete '/logout' => 'devise/sessions#destroy'
  	get '/favorites' => 'users#favorites'
  	get '/signup' => 'registrations#new'
  end

	resources :companies, :only => [:show, :index]
	resources :notepads, :only => :update
  resources :relationships, :only => [:create, :destroy]
  resources :orders

  root :to => 'pages#home'

  match '/services', :to => 'pages#services'
  match '*path', :to => 'pages#home'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  before_destroy :raise_if_last
  
	def raise_if_last
		if AdminUser.count < 2
		  raise "Can't delete last admin user"
		end
	end
	
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :about, :area, :name, :salary

  has_many :relationships, foreign_key: "favorited_id", dependent: :destroy
  has_many :favoriters, through: :relationships, source: :favoriter

  has_many :positions
  has_many :questions
  has_many :requirements
  has_many :responsibilities

  # meta_search limitations
  attr_searchable :name, :salary, :area
  assoc_unsearchable :relationships, :favoriters

  # active_admin scope
  scope :unfinished, where(:about => "") || where(:area => "") || where(:salary => nil)

  def favorited?(user)
    relationships.find_by_favoriter_id(user.id) ? true : false
  end

end

app/models/notepad.rb
class Notepad < ActiveRecord::Base
  attr_accessible :content, :user_id
end

app/models/order.rb
class Order < ActiveRecord::Base

  attr_accessible :user_id, :first_name, :last_name, :card_brand, :card_expires_on, :card_number, :card_verification
  attr_accessor :card_number, :card_verification

  belongs_to :user
  has_many :transactions, :class_name => "OrderTransaction"

  validate :validate_card, :on => :create

  def purchase
    response = GATEWAY.purchase 500, credit_card
    transactions.create :action => "purchase", :amount => 500, :response => response
    user.update_attribute(:paid, true) if response.success?
    response.success?
  end

  private

    def validate_card
      unless credit_card.valid?
        credit_card.errors.full_messages.each do |message|
          errors[:base] << message
        end
      end
    end

    def credit_card
      @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
        type: card_brand,
        number: card_number,
        verification_value: card_verification,
        month: card_expires_on.month,
        year: card_expires_on.year,
        first_name: first_name,
        last_name: last_name
      )
    end
end

app/models/order_transaction.rb
class OrderTransaction < ActiveRecord::Base
  attr_accessible :action, :amount, :authorization, :message, :order_id, :params, :success, :response

  belongs_to :order

  serialize :params

  def response=(response)
    self.success = response.success?
    self.authorization = response.authorization
    self.message = response.message
    self.params = response.params
  rescue ActiveMerchant::ActiveMerchantError => e
    self.success = false
    self.authorization = nil
    self.message = e.message
    self.params = {}
  end
end

app/models/position.rb
class Position < ActiveRecord::Base
  attr_accessible :company_id, :position
  
  belongs_to :company
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :company_id, :question
  
  belongs_to :company
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :favorited_id, :favoriter_id
  
  belongs_to :favoriter, class_name: "User"
  belongs_to :favorited, class_name: "Company"

  validates :favoriter_id, presence: true
  validates :favorited_id, presence: true
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  attr_accessible :company_id, :requirement
  
  belongs_to :company
end

app/models/responsibility.rb
class Responsibility < ActiveRecord::Base
  attr_accessible :company_id, :responsibility
  
  belongs_to :company
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :notes, :resume, :paid
  attr_accessor :resume_content_type

  has_many :relationships, foreign_key: "favoriter_id", dependent: :destroy
  has_many :favorited_companies, through: :relationships, source: :favorited

  has_one :notepad, dependent: :destroy
  has_one :order

  has_attached_file :resume,
                    :storage => :dropbox,
                    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
                    :dropbox_options => {
                      :path => proc { |resume| "resumes/#{id}/#{name}" }
                    }

  validates_attachment :resume, content_type: { content_type: /^application\/(msword|pdf)/ }

  def favorite!(company)
    relationships.create(favorited_id: company.id)
  end

  def favorited?(company)
    relationships.find_by_favorited_id(company.id) ? true : false
  end

  def unfavorite!(company)
    relationships.find_by_favorited_id(company.id).destroy
  end

  def favorites(page)
    favorited_companies.page(page)
  end

  def make_notepad
  	Notepad.create(user_id: self.id, content: "")
  end

  def paid?
    self.paid
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def services
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!

## don't need a profile page right now
#  def show
#  	@user = User.find(current_user.id)
#  end

  def favorites
  	@favorites = current_user.favorites params[:page] #favorited_companies.page(params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# return full title on per page basis
  def full_title(page_title)
    if page_title.empty?
      "intrnhuntr"
    else
      "intrnhuntr | #{page_title}"
    end
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper

  # overriding DeviseHelper
	def devise_error_messages!
		return "" if resource.errors.empty?
    # show all errors in one sentence. I forgot what it shows by default
		messages = resource.errors.full_messages
		flash.now[:error] = messages.join " and "
	end

end

app/helpers/notepads_helper.rb
module NotepadsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

  def order_error_messages!(order)
    return "" if order.errors.empty?
    # only show the first error message. I forgot what it shows by default
    messages = order.errors.full_messages
    flash.now[:error] = messages.first
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_container.html.erb
<div class="container">
  <div class="row">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> fade in">
          <a class="close" data-dismiss="alert"><i class="icon-remove icon-white"></i></a>
          <%= value %>
        </div>
      <% end %>
			<%= render 'layouts/notepad' %> <!-- modal for notepad -->
      <%= yield %>
      <%= render 'layouts/footer' %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "intrnhuntr", root_path %> 
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "intrnhuntr", root_path, class: "brand" %>
      <div class="nav-collapse">
        <ul class="nav pull-right taller">
          <li id="home"><%= link_to "Home",    root_path %></li>
          <li id="services"><%= link_to "Services",    services_path %></li>
          <li id="internships"><%= link_to "Internships", companies_path %></li>
          <% if user_signed_in? %>
          	<li id="noteButton">
          	  <%= ilink_to 'pencil', 'Notes', '#notepad', id: 'show_notes' %>
          	</li>
            <li>
            	<%= ilink_to 'user', '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do %>
            		<%= current_user.name %>
            		<b class="caret"></b>
            	<% end %>
              <ul class="dropdown-menu">
                <!--  <li><  % = link_to "Profile", profile_path %></li> -->
                <li><%= link_to 'Favorites', favorites_path  %></li>
                <li><%= link_to "Settings", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Logout", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_notepad.html.erb
<div id="my_modal" class="modal hide fade" role="dialog">
	<div class="modal-header">
		<% ilink_to 'remove', '', '#', id: 'close_modal' %>
	  <h3>Notes</h3>
	</div>
	<div class="modal-body notepad">
		<% if user_signed_in? %>
			<%= form_for @notepad, remote: true do |f| %>
					<%= f.text_area :content, placeholder: "Notepad" %>
	</div>
	<div class="modal-footer">
		<%= ilink_to 'remove', 'Cancel', '#', class: 'btn btn-danger pull-left', id: 'close_modal' %>
		<%= f.submit "Save", class: "btn btn-medium btn-success pull-right", id: 'save' %>
			<% end %> <!-- end form -->
		<% end %> <!-- end if -->
	</div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
  <%= render 'layouts/container' %>
	<%= debug(params) if Rails.env.development? %> 
</body>
</html>

app/views/pages/home.html.erb
<div class="hero-unit">
  <h1>Welcome to intrnhuntr</h1>
  <h2>People dream of success. We help make it happen</h2>
</div>
<div class="row">
  <div class="span6">
    <h2>Services</h2>
      <p>
        Do you have an idea of where you want your career to start? Well, we can help you get there. We can provide you with the information you need to find and lock in the internship you want.
      </p>
      <p><%= link_to 'More Info', '#', class: "btn" %></p>
  </div>
  <div class="span6">
    <h2>How</h2>
      <p>
      We have worked with a variety of businesses, varying from non-profit to corporate to retail, in order to compile a list of opportunities. And we are ready to show you the opportunities and offer necessary information to grasp them.
      </p>
      <p><%= link_to 'More Info', '#', class: "btn" %></p>
  </div>
</div>

app/views/pages/services.html.erb
<% provide(:title, "Services") %>
<h1>Pages#services</h1>
<p>Find me in app/views/pages/services.html.erb</p>